important_only = false

[[preconfirm]]
  date.start = 2019-02-01
  date.end = 2019-02-25
  price_per_night = 400
  rooms = [
    "1-Bedroom",
    "Studio"
  ]

[[preconfirm]]
  resorts = [
    "Wilderness Lodge",
  ]

[[preconfirm]]
  length_of_stay = 11

[[disc_points]]
  date = 2019-02-01
  points = 100

[[disc_points]]
  price = 15
