[resorts]
key   = "resortKey"

[resorts.values]
AKV   = "resort_jambo"
AKV2  = "resort_kidani"
AULV  = "resort_aulani"
BLT   = "resort_blt"
BCV   = "resort_bcv"
BWALK = "resort_boardwalk"
VWL   = "resort_brv"
WCC   = "resort_ccv"
CFW   = "resort_cfw"
HILTN = "resort_hh"
CLUB  = "resort_okw"
POLYV = "resort_poly"
RVA   = "resort_riviera"
SSR   = "resort_ssr"
VERO  = "resort_vbr"
GCAL  = "resort_vgc"
VGF   = "resort_vgf"
VDH   = "resort_vdh"

[rooms]
key = "roomType"

[rooms.values]
"Studio" = "room_studio"
"Studio w/ Walk-In-Shower" = "room_studiowis"
"Resort Studio" = "room_resort"
"Tower Studio" = "room_tower"
"Duo Studio" = "room_duo"
"Tower Duo Studio" = "room_tower_duo"
"Deluxe Studio" = "room_studio"
"Tower Deluxe Studio" = "room_tower_deluxe"
"Studio - Wheelchair Accessible" = "room_studio"
"1 Bedroom" = "room_one"
"Tower 1-Bedroom" = "room_tower_one"
"1 Bedroom - Wheelchair Accessible" = "room_one"
"1 Bedroom Cabin" = "room_cabin1"
"2 Bedroom" = "room_two"
"Tower 2-Bedroom" = "room_tower_two"
"2 Bedroom - Wheelchair Accessible" = "room_two"
"2 Bedroom Lock Off" = "room_2lo"
"Tower 2-Bedroom Lock-Off" = "room_tower_2lo"
"2 Bedroom Lock-Off - Wheelchair Accessible" = "room_two"
"2 Bedroom Lock Off w/ Walk-In-Shower" = "room_2lowis" # This is a guess, this type currently isn't available so I can't be sure
"Tower Penthouse" = "room_tower_pent"
"3 Bedroom" = "room_three"    # These both are actually the same on the
"Grand Villa" = "room_three"  # DVC side.
"3 Bedroom - Wheelchair Accessible" = "room_three"
"Grand Villa - Wheelchair Accessible" = "room_three"
"Bungalow" = "room_bungalow"
"Cabin" = "room_cabin"
"Hotel" = "room_hotel"
"Inn Room" = "room_inn"
"Treehouse" = "room_treehouse"
"Beach Cottage" = "room_cottage"

[views]
key  = "view"

[views.values]
"Boardwalk"        = "view_boardwalk"
"Island Gardens"   = "view_island"
"Kilimanjaro Club" = "view_kilimanjaro"
"Lake"             = "view_lake"
"Lagoon"           = "view_lagoon"
"Near Hospitality" = "view_hospitality"
"Ocean"            = "view_ocean"
"Preferred"        = "view_preferred"
"Savanna"          = "view_savanna"
"Standard"         = "view_standard"
"Resort"           = "view_standard"
"Theme Park"       = "view_themepark"
"Value"            = "view_value"
"Garden/Pool"      = "view_garden"
"Poolside Gardens" = "view_poolside"
"Premium"          = "view_premium"
