"""Add user model

Revision ID: 1974882d8271
Revises: 3c1c384d9445
Create Date: 2022-05-10 00:17:10.678941

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1974882d8271"
down_revision = "3c1c384d9445"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("last_accessed", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
