"""Add important criteria to User model

Revision ID: 28031748b406
Revises: 1974882d8271
Create Date: 2022-05-17 16:52:54.941222

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "28031748b406"
down_revision = "1974882d8271"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("important_criteria", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "important_criteria")
    # ### end Alembic commands ###
