"""Drop User model to make it easier to change the primary key

Revision ID: 2c63a547a651
Revises: 30771795601d
Create Date: 2022-08-23 23:58:32.551972

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2c63a547a651"
down_revision = "30771795601d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("important_criteria", sa.JSON(), nullable=True),
        sa.Column("last_accessed", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("username", name="users_pkey"),
    )
    # ### end Alembic commands ###
