"""Add static_index column to StaticDataMixin

Revision ID: 359b5da2304f
Revises: 3a38ba5c6894
Create Date: 2023-03-25 12:19:39.201694

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "359b5da2304f"
down_revision = "3a38ba5c6894"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("static_index", sa.Integer(), nullable=True)
        )

    with op.batch_alter_table("characteristics", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("static_index", sa.Integer(), nullable=True)
        )
        batch_op.drop_column("room_index")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("characteristics", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "room_index", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_column("static_index")

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_column("static_index")

    # ### end Alembic commands ###
