"""Increase the String length of url attribute

Revision ID: 39a23132999a
Revises: 464427226fe9
Create Date: 2020-06-09 21:15:47.135946

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "39a23132999a"
down_revision = "464427226fe9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stored_specials",
        "url",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=150),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stored_specials",
        "url",
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
