"""Add PushToken model

Revision ID: 3c1c384d9445
Revises: 4a88e85d1538
Create Date: 2022-05-08 20:39:45.050590

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3c1c384d9445"
down_revision = "4a88e85d1538"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "push_tokens",
        sa.Column("push_token", sa.String(), nullable=False),
        sa.Column("get_errors", sa.Boolean(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("push_token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("push_tokens")
    # ### end Alembic commands ###
