"""Update DVCRS preconfirm fields

Revision ID: 464427226fe9
Revises: ee766ed83bca
Create Date: 2020-04-23 23:34:25.294070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464427226fe9'
down_revision = 'ee766ed83bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stored_specials', 'mention_id', new_column_name='reservation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stored_specials', 'reservation_id', new_column_name='mention_id')
    # ### end Alembic commands ###
