"""Add ParserStatus Table

Revision ID: 4a88e85d1538
Revises: 4b429e00aebf
Create Date: 2020-06-22 15:55:45.743704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a88e85d1538'
down_revision = '4b429e00aebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parser_status',
    sa.Column('parser_status_id', sa.Integer(), nullable=False),
    sa.Column('parser_source', sa.String(length=32), nullable=True),
    sa.Column('healthy', sa.Boolean(), nullable=True),
    sa.Column('empty_okay', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('parser_status_id'),
    sa.UniqueConstraint('parser_source')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parser_status')
    # ### end Alembic commands ###
