"""Add source_name attribute to special

Revision ID: 4b429e00aebf
Revises: 39a23132999a
Create Date: 2020-06-22 14:33:43.724857

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b429e00aebf"
down_revision = "39a23132999a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stored_specials",
        sa.Column("source_name", sa.String(length=32), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stored_specials", "source_name")
    # ### end Alembic commands ###
