"""Add categories

Revision ID: 714e287b67c4
Revises: 93c7710478e8
Create Date: 2022-07-06 15:43:35.117634

"""
from alembic import op
import sqlalchemy as sa

try:
    from sqlalchemy.dialects.postgresql import ENUM as Enum
except ImportError:
    from sqlalchemy import Enum



# revision identifiers, used by Alembic.
revision = '714e287b67c4'
down_revision = '93c7710478e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', Enum('BASE', 'RESORT', 'ROOM', 'VIEW', name='characteristictypes', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_categories'))
    )
    op.add_column('characteristics', sa.Column('category_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(op.f('fk_characteristics_category_id_categories'), 'characteristics', 'categories', ['category_id'], ['category_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_characteristics_category_id_categories'), 'characteristics', type_='foreignkey')
    op.drop_column('characteristics', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
