"""Add Characteristic models - Resort, Room, View

Revision ID: 93c7710478e8
Revises: 82b7b8e092bb
Create Date: 2022-06-29 23:14:45.323724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c7710478e8'
down_revision = '82b7b8e092bb'
branch_labels = None
depends_on = None

characteristictypes = sa.Enum('BASE', 'RESORT', 'ROOM', 'VIEW', name='characteristictypes')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('characteristics',
    sa.Column('characteristic_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', characteristictypes, nullable=False),
    sa.PrimaryKeyConstraint('characteristic_id', name=op.f('pk_characteristics'))
    )
    op.add_column('stored_specials', sa.Column('resort_id', sa.String(), nullable=True))
    op.add_column('stored_specials', sa.Column('room_id', sa.String(), nullable=True))
    op.add_column('stored_specials', sa.Column('view_id', sa.String(), nullable=True))
    op.create_foreign_key(op.f('fk_stored_specials_view_id_characteristics'), 'stored_specials', 'characteristics', ['view_id'], ['characteristic_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_stored_specials_room_id_characteristics'), 'stored_specials', 'characteristics', ['room_id'], ['characteristic_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_stored_specials_resort_id_characteristics'), 'stored_specials', 'characteristics', ['resort_id'], ['characteristic_id'], ondelete='SET NULL')
    op.drop_column('stored_specials', 'room')
    op.drop_column('stored_specials', 'view')
    op.drop_column('stored_specials', 'resort')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stored_specials', sa.Column('resort', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('stored_specials', sa.Column('view', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('stored_specials', sa.Column('room', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_stored_specials_resort_id_characteristics'), 'stored_specials', type_='foreignkey')
    op.drop_constraint(op.f('fk_stored_specials_room_id_characteristics'), 'stored_specials', type_='foreignkey')
    op.drop_constraint(op.f('fk_stored_specials_view_id_characteristics'), 'stored_specials', type_='foreignkey')
    op.drop_column('stored_specials', 'view_id')
    op.drop_column('stored_specials', 'room_id')
    op.drop_column('stored_specials', 'resort_id')
    op.drop_table('characteristics')

    characteristictypes.drop(op.get_bind())
    # ### end Alembic commands ###
