"""Initial Migration

Revision ID: ee766ed83bca
Revises: 
Create Date: 2019-04-20 21:19:16.716932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee766ed83bca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('get_errors', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('phone_numbers',
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('get_errors', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('phone_number')
    )
    op.create_table('status',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_table('stored_specials',
    sa.Column('special_id', sa.String(), nullable=False),
    sa.Column('mention_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('resort', sa.String(length=100), nullable=True),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('special_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stored_specials')
    op.drop_table('status')
    op.drop_table('phone_numbers')
    op.drop_table('emails')
    # ### end Alembic commands ###
